version: '3'
services:
  mshield_reverse_proxy:
    image: markovshield/mshield-demo-reverse-proxy:2.0
    hostname: mshield_reverse_proxy
    ports:
      - "80:80"
      - "443:443"

  mshield_backend:
    image: markovshield/mshield-demo-backend:2.0
    hostname: mshield_backend
    expose:
      - "8888"

  mshield_flink_analyser:
    image: markovshield/mshield-flink-analyser:2.0
    depends_on:
      - jobmanager
      - taskmanager
      - mshield_kafka_clickstreams
    environment:
      JOBMANAGER: 'jobmanager:6123'
      BOOTSTRAP: 'broker:9092'
      ZOOKEEPER: 'zookeeper:2181'
      REDISHOST: 'redis'
      REDISPORT: '6379'

  mshield_flink_modelupdater:
    image: markovshield/mshield-flink-modelupdater:2.0
    depends_on:
      - jobmanager
      - taskmanager
      - mshield_flink_analyser
    environment:
      JOBMANAGER: 'jobmanager:6123'
      BOOTSTRAP: 'broker:9092'
      ZOOKEEPER: 'zookeeper:2181'
      LOOKBACKPERIOD: '20'
      UPDATEINTERVAL: '5'
      SESSIONTIMEOUT: '5'

  mshield_kafka_clickstreams:
    image: markovshield/mshield-kafka-clickstreams:2.0
    hostname: mshield_kafka_clickstreams
    depends_on:
      - broker
      - zookeeper
      - schema_registry
    ports:
      - "7777:7777"
    volumes:
      - ./state-store:/opt/kafka-store
    environment:
      BOOTSTRAP: 'broker:9092'
      RESTHOSTNAME: 'localhost'
      RESTPORT: '7777'
      SCHEMAREGISTRY: 'http://schema_registry:8081'
      ZOOKEEPER: 'zookeeper'

  redis:
    image: redis:3.2.8-alpine
    hostname: redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ./zk-data:/var/lib/zookeeper/data
      - ./zk-txt-logs:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka
    hostname: broker
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    volumes:
      - ./kafka-data:/var/lib/kafka/data
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:9092'

  schema_registry:
    image: confluentinc/cp-schema-registry
    hostname: schema_registry
    depends_on:
      - zookeeper
      - broker
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema_registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'

  jobmanager:
    image: markovshield/flink-manager:1.2.1
    hostname: jobmanager
    depends_on:
      - redis
    expose:
      - "6123"
    ports:
      - "50100-50200:50100-50200"
      - "6123:6123"
      - "48081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager

  taskmanager:
    image: markovshield/flink-manager:1.2.1
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
